"""Demonstrate an OuterMatrix and its generated OuterSweep points."""

from __future__ import annotations

from elims_instruments.characterization import OuterMatrix
from elims_instruments.utils.logger import LOGGER_HELPER, LoggerHelper, get_logger
from examples.bench_setup.dut import ExampleDut, create_example_dut
from examples.characterization.temperature import create_dut_temperature
from examples.characterization.voltages import SupplySetPoints, create_voltages

logger = get_logger(__name__, LoggerHelper.Color.CYAN)


def create_outer_matrix() -> OuterMatrix[ExampleDut]:
    """Create the simulated matrix shared by later examples."""
    return OuterMatrix(
        dut=create_example_dut(),
        temperature=create_dut_temperature(),
        temperature_setpoints=[-40, 25],
        voltages=create_voltages(),
        voltage_setpoints=[
            SupplySetPoints(vdda=1.1),
            SupplySetPoints(vdda=1.3),
        ],
    )


def main() -> None:
    """Apply and report every operating point generated by an OuterMatrix."""
    LOGGER_HELPER.configure()
    matrix = create_outer_matrix()

    for sweep in matrix:
        sweep.reset()
        sweep.set_temperature()
        sweep.enable_temperature()
        sweep.set_voltages()
        sweep.power_up()
        try:
            report = dict(zip(sweep.report_header(), sweep.report_value(), strict=True))
            logger.info("Outer sweep: {}", report)
        finally:
            sweep.power_down()
            sweep.disable_temperature()


if __name__ == "__main__":
    main()
